### ISSUE TITLE
IAS Table is broken for Frenzy/Double Swing/Whirlwind with WIAS input

### ISSUE THREAD

**Issue by Rokoivan69** [Warren1001/IAS_Calculator#17]
When entering WIAS for the primary weapons, the IAS in the table for Frenzy calculations goes up instead of down.
I encountered this with:
Barbarian
Frenzy
Lvl 27 Frenzy
Primary: Berserker Axe with 60 WIAS
Secondary: Berserker Axe with 0 WIAS
IAS table then shows 148 IAS for 10 Frames
With 0 WIAS on both it says 105 IAS for 10 frames

Did I get something wrong or is there an error?
Kind regards and thanks for the tool

**Comment by Warren1001** [comment]
probably an error i overlooked. thought ww and frenzy were handled the same
so i thought i fixed it

**Comment by Warren1001** [comment]
followup, i looked into it and its a bit more complex and dont really feel like devoting all my time immediately to fixing it. instead, what you can do in the meantime: dont use wias for frenzy. instead, average your wias together and thats how much wias you actually have on the 0 wias table. this isnt 100% correct, and you might need an additional ias or two if you're right on/near a breakpoint to actually meet it, but for most cases its correct

**Comment by Warren1001** [comment]
There isn't necessarily a bug with what's going on, the information presented is just slightly confusing and doesn't behave the way one would expect it to despite being correct. I'm still thinking of a way to better present information correctly, but this is more of a cosmetic/presentation-of-information issue rather than a bug.
