### ISSUE TITLE
mighty scepter is missing from primary weapons for palladin

### ISSUE THREAD

**Issue by Jieiku** [Warren1001/IAS_Calculator#29]
mighty scepter is missing from primary weapons for palladin.

I ended up picking crystal sword because it shows [0], arreat summit shows a [0] for the attack speed, so I hope my assumption here is correct.

**Comment by Warren1001** [comment]
your assumption is correct. which skill are you testing with? might scepter shows for me using the standard skill. its possible you chose the oskill zeal which corresponds to passion, which is a 4os sword. since mighty scepter doesn't have 4os, it is not an option. paladin has his own zeal in his group of skills

**Comment by Jieiku** [comment]
I think your correct, I see mighty scepter i the list now. Appreciate the help, excellent tool!
